In [49]:
import torch
import torch.nn as nn

import numpy as np
import pandas as pd

In [23]:
import math

In [22]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [ ]:
class TokenEmbedding(nn.Module):

    def __init__(self, tokens):
        super().__init()
        
        self.te = nn.Linear()


    def forward(x):

        x = self.te(x)

        x = x + pe

        

In [ ]:
class PsitionEncoding(nn.Module):
    def __init__(self, seq_len, d_model):
        super().__init__()
        pe = torch.zeros(seq_len, d_model)
        
        pos = torch.arange(0, seq_len).unsqueeze(-1)
        i = torch.arange(0, d_model, 2).unsqueeze(0)
        pe[:, 0::2] = torch.sin(pos/10000**(i/d_model))
        pe[:, 1::2] = torch.cos(pos/10000**(i/d_model))
        
        # for pos in range(pe.shape[0]):
        #     for i in range(pe.shape[1]):
        #         if i % 2 == 0:
        #             pe[pos, i] = np.sin(pos/10000**(i/d_model))
        #         else:
        #             pe[pos, i] = np.cos(pos/10000**((i-1)/d_model))
        
        # need to register as buffer to let Pytorch not train the weights
        self.register_buffer("pe", pe) # (seq_len, d_model)

    def forward(self, x):
        x = x + self.pe.unsqueeze(0) # (B, seq_len, d_model) + (1, seq_len, d_model) --> Pytorch broadcasting takes care of batch dimension
        return x

In [80]:
seq_len = 7
d_model = 13
pe = torch.zeros(seq_len, d_model)

pos = torch.arange(0, seq_len).unsqueeze(-1)

i = torch.arange(0, d_model, 2).unsqueeze(0)
pe[:, 0::2] = torch.sin(pos/10000**(i/d_model))

i = torch.arange(1, d_model, 2).unsqueeze(0)
pe[:, 1::2] = torch.sin(pos/10000**(i/d_model))

In [81]:
pe

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  4.7273e-01,  2.4008e-01,  1.1909e-01,  5.8746e-02,
          2.8939e-02,  1.4251e-02,  7.0170e-03,  3.4551e-03,  1.7013e-03,
          8.3768e-04,  4.1246e-04,  2.0309e-04],
        [ 9.0930e-01,  8.3315e-01,  4.6611e-01,  2.3649e-01,  1.1729e-01,
          5.7853e-02,  2.8498e-02,  1.4034e-02,  6.9102e-03,  3.4025e-03,
          1.6754e-03,  8.2493e-04,  4.0618e-04],
        [ 1.4112e-01,  9.9562e-01,  6.6488e-01,  3.5053e-01,  1.7543e-01,
          8.6719e-02,  4.2740e-02,  2.1050e-02,  1.0365e-02,  5.1037e-03,
          2.5130e-03,  1.2374e-03,  6.0928e-04],
        [-7.5680e-01,  9.2154e-01,  8.2476e-01,  4.5957e-01,  2.3296e-01,
          1.1551e-01,  5.6973e-02,  2.8064e-02,  1.3820e-02,  6.8050e-03,
          3.3507e-03,  1.6498e-03,  8.1237e-04],
        [-9.589

In [78]:
pos = torch.arange(0, 6).view(6, 1)
i = torch.arange(0, 13, 2).view(1, 7)
odd = torch.sin(pos/10000**(i/d_model))

In [76]:
pos = torch.arange(0, 6).unsqueeze(-1)
i = torch.arange(0, 13, 2).unsqueeze(0)
odd = np.sin(pos/10000**(i/d_model))

/tmp/ipykernel_2310717/2238295526.py:3: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  odd = np.sin(pos/10000**(i/d_model))


In [74]:
torch.arange(0, 6).unsqueeze(-1).shape

torch.Size([6, 1])

In [77]:
odd

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.3877,  0.1578,  0.0631,  0.0251,  0.0100,  0.0040],
        [ 0.9093,  0.7147,  0.3117,  0.1259,  0.0502,  0.0200,  0.0080],
        [ 0.1411,  0.9300,  0.4578,  0.1882,  0.0753,  0.0300,  0.0119],
        [-0.7568,  0.9998,  0.5923,  0.2497,  0.1003,  0.0400,  0.0159],
        [-0.9589,  0.9132,  0.7121,  0.3103,  0.1253,  0.0500,  0.0199]])

In [65]:
np.sin(pos/10000**(i/5))

RuntimeError: The size of tensor a (6) must match the size of tensor b (7) at non-singleton dimension 0

In [69]:
torch.arange(0, 6).view(6, 1).shape

torch.Size([6, 1])

In [68]:
torch.arange(0, 6).shape

torch.Size([6])

In [52]:
torch.arange(0, 13, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12])

In [53]:
torch.arange(1, 13, 2)

tensor([ 1,  3,  5,  7,  9, 11])

In [54]:
aa = torch.zeros(7, 13)
aa

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
aa = torch.zeros(7, 13)
aa[:, 0::2] = 1

In [62]:
aa

tensor([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [55]:
aa[3, 5]

tensor(0.)

In [43]:
aa[1, 2]

tensor(0.)

In [44]:
np.sin(2/10000**(3/d_model))

np.float64(0.48151044690858236)

In [45]:
d_model = 20
for pos in range(aa.shape[0]):
    for i in range(aa.shape[1]):
        if i % 2 == 0:
            aa[pos, i] = np.sin(pos/10000**(i/d_model))
        else:
            aa[pos, i] = np.sin(pos/10000**(i/d_model))
    

In [50]:
pd.DataFrame(aa)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.841471,0.589918,0.387674,0.248555,0.157827,0.099833,0.063054,0.039800,0.025116,0.015848,0.010000,0.006310,0.003981
2,0.909297,0.952674,0.714713,0.481510,0.311697,0.198669,0.125857,0.079537,0.050217,0.031693,0.019999,0.012619,0.007962
3,0.141120,0.948580,0.929966,0.684244,0.457755,0.295520,0.188159,0.119148,0.075285,0.047529,0.029996,0.018928,0.011943
4,-0.756802,0.579213,0.999766,0.844030,0.592338,0.389418,0.249712,0.158571,0.100306,0.063353,0.039989,0.025236,0.015924
5,-0.958924,-0.013194,0.913195,0.950842,0.712073,0.479426,0.310272,0.197742,0.125264,0.079162,0.049979,0.031543,0.019904
6,-0.279415,-0.600520,0.683794,0.997974,0.813960,0.564642,0.369596,0.236599,0.150143,0.094950,0.059964,0.037848,0.023884


In [ ]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, h):
        super().__init__()
        self.d_model = d_model
        self.h = h
        assert d_model % h == 0, "d_model should be divisible by h"
        self.d_k = d_model // h
        
        self.w_q = nn.Linear(d_model, d_model, bias=False)
        self.w_k = nn.Linear(d_model, d_model, bias=False)
        self.w_v = nn.Linear(d_model, d_model, bias=False)
        
        self.w_o = nn.Linear(d_model, d_model, bias=False)

    @staticmethod
    def attention(q, k, v, mask=None):
        d_k = q.shape[-1]
        attention_scores = q @ k.transpose(-2, -1) / math.sqrt(d_k) # skippin B, h (seq_len, d_k) @ (d_k, seq_len) --> (seq_len, seq_len) or (B, h, seq_len, seq_len)
        if mask is not None:
            # apply mask
            pass
        attention_scores = attention_scores.softmax(dim=-1)
        x = attention_scores @ v # (seq_len, seq_len) @ (seq_len, d_k) --> (seq_len, d_k) or (B, h, seq_len, d_k)
        return x, attention_scores

    def forward(self, x): # x --> (B, seq_len, d_model)
        q = self.w_q(x) # --> (B, seq_len, d_model)
        k = self.w_k(x) # --> (B, seq_len, d_model)
        v = self.w_v(x) # --> (B, seq_len, d_model)

        q = q.view(q.shape[0], q.shape[1], self.h, self.d_k).transpose(1, 2) # (B, h, seq_len, d_k)
        k = k.view(k.shape[0], k.shape[1], self.h, self.d_k).transpose(1, 2) # (B, h, seq_len, d_k)
        v = v.view(v.shape[0], v.shape[1], self.h, self.d_k).transpose(1, 2) # (B, h, seq_len, d_k)

        x, self.attention_scores = MultiHeadAttention.attention(q, k, v) # (B, h, seq_len, d_k)
        x = x.transpose(1, 2).contiguou() # (B, seq_len, h, d_k)
        x = x.view(x.shape[0], x.shape[1], int(self.h * self.d_k)) # (B, seq_len, d_model)
        
        x = self.w_o(x)
        return x

In [3]:
class TransformerBlock(nn.Module):

    def __int__(self):
        super().__init__()

        